// `vibeterm settings`：站点、快捷键、通知、webhook、LLM、TLS、隧道、本机、账号安全。

import { type SubHandler, runSubs } from '../core/cmd';
import { tls, local, system, tunnel } from './settings-local';
import { telegram, weixin } from './settings-messaging';
import { localAuth, passkey, passwd, totp } from './settings-security';
import {
  domainAccess,
  llm,
  notifications,
  restart,
  shortcuts,
  site,
  webhooks,
} from './settings-site';
import type { Command } from './types';

export const FLAGS = {
  yes: 'boolean',
  body: 'string',
  enabled: 'string',
  on: 'boolean',
  off: 'boolean',
  url: 'string',
  secret: 'string',
  'secret-stdin': 'boolean',
  'secret-file': 'string',
  events: 'string',
  name: 'string',
  protocol: 'string',
  'base-url': 'string',
  'api-key': 'string',
  'api-key-stdin': 'boolean',
  'api-key-file': 'string',
  'skip-self-revoke': 'boolean',
  hostname: 'string',
  version: 'string',
  'expected-role': 'string',
  'target-role': 'string',
  acknowledge: 'boolean',
  action: 'string',
  'auto-start': 'string',
  'trust-proxy': 'string',
  'full-reset': 'boolean',
  'new-password': 'string',
  'new-password-stdin': 'boolean',
  'new-password-file': 'string',
  code: 'string',
  'totp-secret': 'string',
  user: 'string',
  password: 'string',
  'password-stdin': 'boolean',
  'password-file': 'string',
  token: 'string',
  'token-stdin': 'boolean',
  'token-file': 'string',
  'allow-auth': 'string',
  'allow-commands': 'string',
} as const;

const USAGE = [
  'Usage: vibeterm settings <group> …',
  '',
  '  site get|set <key> <value>     GET/PATCH /api/settings/site',
  '  shortcuts get|set              GET/PATCH /api/settings/terminal-shortcuts (set needs --body)',
  '  restart [--yes]                POST /api/settings/restart',
  '  notifications mesh get|set on|off',
  '  webhooks ls|add|rm|edit        edit = rm+add with --body',
  '  llm providers ls|add|edit|rm|refresh-models',
  '  llm get|set                    GET/PATCH /api/llm/settings (set needs --body)',
  '  domain-access get|set on|off   GET/PATCH /api/system/domain-access',
  '  tls get|set|renew|ca           GET/PUT /api/tls, POST /api/tls/renew, GET /api/tls/ca.crt',
  '  tunnel status|<action>         GET /api/tunnel/status or POST /api/tunnel/actions',
  '  system info|addresses|update-check|upgrade status|start',
  '  local status|leave|direct      GET /api/local/status; POST /api/local/leave|direct (--node honoured for direct)',
  '  passwd [--full-reset]          keylog rotate-root-keep (or rotate-root); VIBETERM_PASSWORD / VIBETERM_NEW_PASSWORD',
  '  totp enable|disable            set-totp (prints secret + otpauth, verifies --code) / clear-totp',
  '  passkey ls|rm <id> [--yes]     GET /api/auth/passkeys; keylog remove-passkey (register in the browser)',
  '  local-auth bootstrap|set       POST /api/auth/local/bootstrap; POST /api/auth/local',
  '  telegram ls|add|edit|rm|chats  /api/settings/telegram/bots and …/chats',
  '  weixin ls|add|edit|rm|test|login|users  /api/settings/weixin/accounts',
  '',
  'Complex bodies accept --body <json>|@file like `vibeterm api`.',
  'Secrets: --secret-stdin/--secret-file/VIBETERM_WEBHOOK_SECRET, --api-key-stdin/--api-key-file/VIBETERM_LLM_API_KEY, --token-stdin/--token-file/VIBETERM_TELEGRAM_TOKEN, --new-password-stdin/--new-password-file/VIBETERM_NEW_PASSWORD.',
  'argv --secret/--api-key/--token/--password/--new-password warn on stderr. local leave self-revokes (VIBETERM_PASSWORD) unless --skip-self-revoke.',
  '--json prints the gateway payload unchanged.',
].join('\n');

const HANDLERS: Record<string, SubHandler> = {
  site,
  shortcuts,
  restart,
  notifications,
  webhooks,
  llm,
  'domain-access': domainAccess,
  tls,
  tunnel,
  system,
  local,
  passwd,
  totp,
  passkey,
  'local-auth': localAuth,
  telegram,
  weixin,
};

export const command: Command = {
  name: 'settings',
  summary: 'read and write site settings',
  usage: USAGE,
  flags: FLAGS,
  run: (ctx, argv) => runSubs(ctx, argv, FLAGS, HANDLERS, 'run: vibeterm settings --help'),
};
