CREATE TABLE `tls_config` (
	`id` integer PRIMARY KEY NOT NULL,
	`mode` text DEFAULT 'none' NOT NULL,
	`tls_port` integer DEFAULT 9443 NOT NULL,
	`bind_host` text DEFAULT '0.0.0.0' NOT NULL,
	`sans` text DEFAULT '[]' NOT NULL,
	`ca_cert_pem` text,
	`ca_key_enc` text,
	`cert_pem` text,
	`key_enc` text,
	`cert_not_before` integer,
	`cert_not_after` integer,
	`acme_email` text,
	`acme_domain` text,
	`acme_challenge` text,
	`acme_staging` integer DEFAULT false NOT NULL,
	`acme_cf_token_enc` text,
	`acme_account_key_enc` text,
	`acme_account_url` text,
	`acme_status` text DEFAULT 'idle' NOT NULL,
	`acme_last_error` text,
	`acme_last_attempt_at` integer,
	`acme_next_renew_at` integer,
	`updated_at` integer NOT NULL,
	CONSTRAINT "tls_config_singleton_check" CHECK("tls_config"."id" = 1),
	CONSTRAINT "tls_config_mode_check" CHECK("tls_config"."mode" in ('none', 'external', 'selfsigned', 'acme')),
	CONSTRAINT "tls_config_acme_challenge_check" CHECK("tls_config"."acme_challenge" is null or "tls_config"."acme_challenge" in ('http-01', 'dns-01')),
	CONSTRAINT "tls_config_acme_status_check" CHECK("tls_config"."acme_status" in ('idle', 'pending', 'ok', 'error'))
);
