import { describe, expect, it } from 'bun:test';
import { mergeClassNames } from './class-merge';

// 下面的期望值全部是 tailwind-merge 3.4.0（默认配置、Tailwind CSS v4）的实际输出，
// 用来锁定去掉该依赖之后 cn() 的行为不变。
const CASES: [input: string, expected: string][] = [
  // 内边距 / 外边距
  ['p-2 p-4', 'p-4'],
  ['p-2 px-4', 'p-2 px-4'],
  ['px-4 p-2', 'p-2'],
  ['p-2 pt-4', 'p-2 pt-4'],
  ['pt-4 p-2', 'p-2'],
  ['px-2 pl-4', 'px-2 pl-4'],
  ['pl-4 px-2', 'px-2'],
  ['py-2 pt-1 pb-3', 'py-2 pt-1 pb-3'],
  ['p-4 px-2 pt-1', 'p-4 px-2 pt-1'],
  ['p-px p-0', 'p-0'],
  ['p-0.5 p-[3px]', 'p-[3px]'],
  ['p-[3px] p-2', 'p-2'],
  ['ps-2 p-4', 'p-4'],
  ['p-4 ps-2', 'p-4 ps-2'],
  ['pe-2 pr-3', 'pe-2 pr-3'],
  ['m-2 m-4', 'm-4'],
  ['m-2 mx-4', 'm-2 mx-4'],
  ['mx-4 m-2', 'm-2'],
  ['mx-2 ml-4', 'mx-2 ml-4'],
  ['ml-4 mx-2', 'mx-2'],
  ['my-2 mt-1 mb-3', 'my-2 mt-1 mb-3'],
  ['m-auto mx-auto', 'm-auto mx-auto'],
  ['-mt-px mt-2', 'mt-2'],
  ['mt-2 -mt-px', '-mt-px'],
  ['-mx-1 mx-2', 'mx-2'],
  ['ml-[-8px] ml-2', 'ml-2'],
  ['mr-auto mr-2', 'mr-2'],
  // 尺寸
  ['size-4 w-6', 'size-4 w-6'],
  ['w-6 size-4', 'size-4'],
  ['size-4 h-6', 'size-4 h-6'],
  ['h-6 size-4', 'size-4'],
  ['w-4 h-4 size-6', 'size-6'],
  ['size-full size-4', 'size-4'],
  ['h-4 h-full', 'h-full'],
  ['w-full w-(--sidebar-width)', 'w-(--sidebar-width)'],
  ['w-(--sidebar-width) w-full', 'w-full'],
  ['h-[calc(100%-1px)] h-4', 'h-4'],
  ['min-h-0 min-h-full', 'min-h-full'],
  ['max-w-sm max-w-[80vw]', 'max-w-[80vw]'],
  ['min-w-0 min-w-max', 'min-w-max'],
  ['max-h-[85dvh] max-h-full', 'max-h-full'],
  ['w-1/2 w-full', 'w-full'],
  ['h-px h-1', 'h-1'],
  ['w-fit w-auto', 'w-auto'],
  // 定位
  ['inset-0 top-2', 'inset-0 top-2'],
  ['top-2 inset-0', 'inset-0'],
  ['inset-x-0 left-2', 'inset-x-0 left-2'],
  ['left-2 inset-x-0', 'inset-x-0'],
  ['inset-y-0 top-1 bottom-1', 'inset-y-0 top-1 bottom-1'],
  ['inset-0 inset-x-2', 'inset-0 inset-x-2'],
  ['start-1 inset-0', 'inset-0'],
  ['inset-0 start-1', 'inset-0 start-1'],
  ['top-1/2 top-0', 'top-0'],
  ['-left-1 left-0', 'left-0'],
  ['absolute relative', 'relative'],
  ['relative fixed sticky', 'sticky'],
  ['z-10 z-50', 'z-50'],
  // 圆角
  ['rounded rounded-lg', 'rounded-lg'],
  ['rounded-lg rounded-t-xl', 'rounded-lg rounded-t-xl'],
  ['rounded-t-xl rounded-lg', 'rounded-lg'],
  ['rounded-md rounded-tl-sm', 'rounded-md rounded-tl-sm'],
  ['rounded-t-xl rounded-tl-none', 'rounded-t-xl rounded-tl-none'],
  ['rounded-full rounded-[2px]', 'rounded-[2px]'],
  ['rounded-[min(var(--radius-md),10px)] rounded-sm', 'rounded-sm'],
  // 边框
  ['border border-2', 'border-2'],
  ['border-2 border', 'border'],
  ['border border-border', 'border border-border'],
  ['border-border border-primary', 'border-primary'],
  ['border border-t-0', 'border border-t-0'],
  ['border-t-0 border', 'border'],
  ['border-t border-t-transparent', 'border-t border-t-transparent'],
  ['border-b border-x', 'border-b border-x'],
  ['border-dashed border-solid', 'border-solid'],
  ['border-dashed border-2', 'border-dashed border-2'],
  ['border-none border-border', 'border-none border-border'],
  ['border-l-2 border-l', 'border-l'],
  ['border-collapse border-separate', 'border-separate'],
  ['border-border/50 border-border/60', 'border-border/60'],
  // 环 / 轮廓 / 阴影
  ['ring-1 ring-2', 'ring-2'],
  ['ring-2 ring-primary', 'ring-2 ring-primary'],
  ['ring-primary ring-ring/30', 'ring-ring/30'],
  ['ring-inset ring-2', 'ring-inset ring-2'],
  ['outline outline-1', 'outline-1'],
  ['outline-none outline-hidden', 'outline-hidden'],
  ['outline-hidden outline-ring', 'outline-hidden outline-ring'],
  ['outline-1 outline-2', 'outline-2'],
  ['shadow shadow-lg', 'shadow-lg'],
  ['shadow-sm shadow-none', 'shadow-none'],
  ['shadow-md shadow-[0_0_0_1px_hsl(var(--x))]', 'shadow-[0_0_0_1px_hsl(var(--x))]'],
  ['shadow-lg shadow-primary', 'shadow-lg shadow-primary'],
  ['shadow-primary shadow-lg', 'shadow-primary shadow-lg'],
  // 文本
  ['text-sm text-lg', 'text-lg'],
  ['text-sm text-muted-foreground', 'text-sm text-muted-foreground'],
  ['text-muted-foreground text-foreground', 'text-foreground'],
  ['text-sm text-center', 'text-sm text-center'],
  ['text-center text-left', 'text-left'],
  ['text-xs text-[10px]', 'text-[10px]'],
  ['text-[0.85em] text-sm', 'text-sm'],
  ['leading-tight text-sm', 'text-sm'],
  ['text-sm leading-tight', 'text-sm leading-tight'],
  ['text-sm/6 leading-4', 'text-sm/6 leading-4'],
  ['leading-4 text-sm/6', 'text-sm/6'],
  ['text-balance text-pretty', 'text-pretty'],
  ['text-nowrap whitespace-nowrap', 'text-nowrap whitespace-nowrap'],
  ['truncate text-ellipsis', 'text-ellipsis'],
  ['underline no-underline', 'no-underline'],
  ['underline-offset-2 underline-offset-4', 'underline-offset-4'],
  ['uppercase capitalize', 'capitalize'],
  ['font-medium font-semibold', 'font-semibold'],
  ['font-mono font-medium', 'font-mono font-medium'],
  ['font-medium font-mono', 'font-medium font-mono'],
  ['tracking-tight tracking-wide', 'tracking-wide'],
  ['line-clamp-1 line-clamp-2', 'line-clamp-2'],
  ['line-clamp-1 block', 'line-clamp-1 block'],
  ['block line-clamp-1', 'line-clamp-1'],
  ['line-clamp-2 overflow-auto', 'line-clamp-2 overflow-auto'],
  ['overflow-auto line-clamp-2', 'line-clamp-2'],
  ['tabular-nums normal-nums', 'normal-nums'],
  // 背景 / 颜色
  ['bg-muted bg-primary', 'bg-primary'],
  ['bg-primary/10 bg-primary', 'bg-primary'],
  ['bg-primary bg-primary/10', 'bg-primary/10'],
  ['bg-transparent bg-white', 'bg-white'],
  ['bg-clip-padding bg-muted', 'bg-clip-padding bg-muted'],
  ['bg-[url(a.png)] bg-cover', 'bg-[url(a.png)] bg-cover'],
  ['bg-cover bg-contain', 'bg-contain'],
  ['bg-center bg-top', 'bg-top'],
  ['fill-foreground fill-none', 'fill-none'],
  ['accent-current accent-primary', 'accent-primary'],
  ['text-primary bg-primary', 'text-primary bg-primary'],
  // 布局
  ['flex grid', 'grid'],
  ['grid hidden', 'hidden'],
  ['flex flex-col flex-row', 'flex flex-row'],
  ['flex-1 flex-none', 'flex-none'],
  ['basis-32 flex-1', 'flex-1'],
  ['flex-1 basis-32', 'flex-1 basis-32'],
  ['shrink-0 shrink', 'shrink'],
  ['items-center items-start', 'items-start'],
  ['justify-between justify-center', 'justify-center'],
  ['self-center self-end', 'self-end'],
  ['place-items-center place-items-start', 'place-items-start'],
  ['gap-2 gap-4', 'gap-4'],
  ['gap-2 gap-x-4', 'gap-2 gap-x-4'],
  ['gap-x-4 gap-2', 'gap-2'],
  ['gap-x-2 gap-y-4', 'gap-x-2 gap-y-4'],
  ['grid-cols-2 grid-cols-[1fr_auto]', 'grid-cols-[1fr_auto]'],
  ['grid-rows-[1fr] grid-rows-2', 'grid-rows-2'],
  ['col-span-2 col-start-2', 'col-span-2 col-start-2'],
  ['row-span-2 row-start-1', 'row-span-2 row-start-1'],
  ['space-y-2 space-y-4', 'space-y-4'],
  ['space-x-2 space-y-2', 'space-x-2 space-y-2'],
  ['auto-rows-min auto-rows-max', 'auto-rows-max'],
  ['contents block', 'block'],
  // 溢出 / 滚动 / 交互
  ['overflow-hidden overflow-auto', 'overflow-auto'],
  ['overflow-hidden overflow-x-auto', 'overflow-hidden overflow-x-auto'],
  ['overflow-x-auto overflow-hidden', 'overflow-hidden'],
  ['overscroll-contain overscroll-auto', 'overscroll-auto'],
  ['overscroll-none overscroll-x-none', 'overscroll-none overscroll-x-none'],
  ['touch-none touch-pan-y', 'touch-pan-y'],
  ['touch-pan-y touch-none', 'touch-none'],
  ['select-none select-text', 'select-text'],
  ['cursor-pointer cursor-default', 'cursor-default'],
  ['pointer-events-none pointer-events-auto', 'pointer-events-auto'],
  ['resize-none resize-y', 'resize-y'],
  ['scroll-my-1 scroll-mt-2', 'scroll-my-1 scroll-mt-2'],
  ['scroll-mt-2 scroll-my-1', 'scroll-my-1'],
  // 变换 / 动效
  ['translate-x-1 translate-x-2', 'translate-x-2'],
  ['translate-x-1 translate-none', 'translate-none'],
  ['translate-none translate-x-1', 'translate-none translate-x-1'],
  ['-translate-x-1/2 translate-x-px', 'translate-x-px'],
  ['rotate-45 rotate-90', 'rotate-90'],
  ['scale-[1.03] scale-100', 'scale-100'],
  ['transition-all transition-colors', 'transition-colors'],
  ['transition transition-none', 'transition-none'],
  ['duration-150 duration-(--tmex-motion-fast)', 'duration-(--tmex-motion-fast)'],
  ['ease-in ease-out', 'ease-out'],
  ['animate-spin animate-none', 'animate-none'],
  ['opacity-0 opacity-100', 'opacity-100'],
  ['blur blur-sm', 'blur-sm'],
  ['backdrop-blur backdrop-blur-sm', 'backdrop-blur-sm'],
  ['filter grayscale', 'filter grayscale'],
  ['grayscale grayscale-0', 'grayscale-0'],
  // 变体前缀
  ['hover:bg-muted hover:bg-primary', 'hover:bg-primary'],
  ['bg-muted hover:bg-primary', 'bg-muted hover:bg-primary'],
  ['hover:bg-muted bg-primary', 'hover:bg-muted bg-primary'],
  ['sm:p-2 sm:p-4', 'sm:p-4'],
  ['p-2 sm:p-4', 'p-2 sm:p-4'],
  ['sm:p-4 p-2', 'sm:p-4 p-2'],
  ['dark:bg-input/30 dark:bg-transparent', 'dark:bg-transparent'],
  ['hover:focus:p-2 focus:hover:p-4', 'focus:hover:p-4'],
  ['focus:hover:p-4 hover:focus:p-2', 'hover:focus:p-2'],
  ['group-hover:opacity-100 group-hover:opacity-0', 'group-hover:opacity-0'],
  ['data-[state=open]:rotate-90 data-[state=open]:rotate-45', 'data-[state=open]:rotate-45'],
  ['[&_svg]:size-3 [&_svg]:size-4', '[&_svg]:size-4'],
  ['[&_svg]:size-4 [&>svg]:size-3', '[&_svg]:size-4 [&>svg]:size-3'],
  ['*:p-2 p-4', '*:p-2 p-4'],
  ['p-4 *:p-2', 'p-4 *:p-2'],
  ['after:absolute after:relative', 'after:relative'],
  [
    'md:peer-data-[variant=inset]:m-2 md:peer-data-[variant=inset]:m-0',
    'md:peer-data-[variant=inset]:m-0',
  ],
  ['motion-reduce:transition-none transition-all', 'motion-reduce:transition-none transition-all'],
  ['aria-invalid:ring-2 aria-invalid:ring-3', 'aria-invalid:ring-3'],
  ['has-[:focus-visible]:ring-2 has-[:focus-visible]:ring-4', 'has-[:focus-visible]:ring-4'],
  [
    'supports-backdrop-filter:backdrop-blur-xs backdrop-blur',
    'supports-backdrop-filter:backdrop-blur-xs backdrop-blur',
  ],
  [
    '[@media(any-pointer:coarse)]:h-10 [@media(any-pointer:coarse)]:h-9',
    '[@media(any-pointer:coarse)]:h-9',
  ],
  [
    'in-data-[side=left]:cursor-w-resize cursor-grab',
    'in-data-[side=left]:cursor-w-resize cursor-grab',
  ],
  // important / 负值 / 任意值 / 任意属性
  ['p-2 p-4!', 'p-2 p-4!'],
  ['p-4! p-2', 'p-4! p-2'],
  ['p-2! p-4!', 'p-4!'],
  ['!p-2 p-4', '!p-2 p-4'],
  ['p-4 !p-2', 'p-4 !p-2'],
  ['p-2! !p-4', '!p-4'],
  [
    'group-data-[collapsible=icon]:p-0! group-data-[collapsible=icon]:p-2!',
    'group-data-[collapsible=icon]:p-2!',
  ],
  ['[&>svg]:size-3! [&>svg]:size-4', '[&>svg]:size-3! [&>svg]:size-4'],
  ['top-1/2! top-0', 'top-1/2! top-0'],
  ['!justify-start justify-end', '!justify-start justify-end'],
  ['[overflow-wrap:break-word] [overflow-wrap:normal]', '[overflow-wrap:normal]'],
  ['[scrollbar-width:none] [scrollbar-width:auto]', '[scrollbar-width:auto]'],
  ['[color:red] [color:blue]', '[color:blue]'],
  ['[color:red] text-primary', '[color:red] text-primary'],
  ['[--foo:bar] [--foo:baz]', '[--foo:baz]'],
  ['bg-[#fff] bg-[rgb(0,0,0)]', 'bg-[rgb(0,0,0)]'],
  ['w-[calc(100%-1px)] w-[calc(100%-2px)]', 'w-[calc(100%-2px)]'],
  ['h-[var(--x)] h-[var(--y)]', 'h-[var(--y)]'],
  ['text-[length:20px] text-[color:red]', 'text-[length:20px] text-[color:red]'],
  ['text-[color:red] text-[length:20px]', 'text-[color:red] text-[length:20px]'],
  // 未知类 / 去重 / 顺序
  ['my-custom p-2 my-custom', 'my-custom p-2 my-custom'],
  ['p-2 p-2', 'p-2'],
  ['p-2 unknown p-4', 'unknown p-4'],
  ['unknown p-2 unknown2 p-4', 'unknown unknown2 p-4'],
  ['group peer p-2', 'group peer p-2'],
  ['sr-only not-sr-only', 'not-sr-only'],
  ['container p-2', 'container p-2'],
  ['foo-bar baz-qux', 'foo-bar baz-qux'],
  [
    'flex items-center justify-between gap-2 p-4 text-sm font-medium',
    'flex items-center justify-between gap-2 p-4 text-sm font-medium',
  ],
];

const EDGE_CASES: [input: string, expected: string][] = [
  ['', ''],
  [' ', ''],
  ['  p-2   p-4  ', 'p-4'],
  ['p-2\n\np-4', 'p-4'],
  ['p-', 'p-'],
  ['-', '-'],
  ['p--2', 'p--2'],
  ['[]', '[]'],
  ['[:]', '[:]'],
  ['[a:]', '[a:]'],
  ['[:b]', '[:b]'],
  ['hover:', 'hover:'],
  [':p-2', ':p-2'],
  ['p-2/', 'p-2/'],
  ['/p-2', '/p-2'],
  ['!', '!'],
  ['!!p-2', '!!p-2'],
  ['p-2!!', 'p-2!!'],
];

describe('mergeClassNames', () => {
  for (const [input, expected] of CASES) {
    it(`合并 ${input}`, () => {
      expect(mergeClassNames(input)).toBe(expected);
    });
  }

  for (const [input, expected] of EDGE_CASES) {
    it(`边界输入 ${JSON.stringify(input)}`, () => {
      expect(mergeClassNames(input)).toBe(expected);
    });
  }

  it('未识别的类名按原顺序保留', () => {
    expect(mergeClassNames('foo p-2 bar p-4 baz')).toBe('foo bar p-4 baz');
  });

  it('重复调用（命中缓存）结果一致', () => {
    const input = 'flex items-center gap-2 p-2 p-4';
    const first = mergeClassNames(input);
    expect(mergeClassNames(input)).toBe(first);
    expect(first).toBe('flex items-center gap-2 p-4');
  });

  it('缓存超出上限后仍然正确', () => {
    for (let index = 0; index < 600; index += 1) mergeClassNames(`p-${index} p-4`);
    expect(mergeClassNames('p-2 p-4')).toBe('p-4');
  });
});
