// 生成 packages/theme/src/tokens.generated.css：终端快捷按钮 CSS 变量（真源 = terminal-shortcut-tokens.ts）
// 用法：bun scripts/theme/build-shortcut-tokens.ts

import fs from 'node:fs';
import path from 'node:path';
import { TERMINAL_SHORTCUT_TOKENS } from '../../packages/theme/src/terminal-shortcut-tokens';

const OUT = path.join(import.meta.dir, '../../packages/theme/src/tokens.generated.css');

const css = `/* Auto-generated by scripts/theme/build-shortcut-tokens.ts — do not edit.
   真源：packages/theme/src/terminal-shortcut-tokens.ts（seoul256 via @tmex/shared/appearance） */

:root {
  --terminal-shortcut-fg: ${TERMINAL_SHORTCUT_TOKENS.light.fg};
  --terminal-shortcut-bg: ${TERMINAL_SHORTCUT_TOKENS.light.bg};
}

.dark {
  --terminal-shortcut-fg: ${TERMINAL_SHORTCUT_TOKENS.dark.fg};
  --terminal-shortcut-bg: ${TERMINAL_SHORTCUT_TOKENS.dark.bg};
}
`;

fs.writeFileSync(OUT, css);
console.log(`[theme] wrote ${OUT}`);
