export {
  DC_PROMOTE_ADDITIVE_MS as DC_PROMOTE_ADDITIVE_MS_DEFAULT,
  DC_PROMOTE_BACKOFF_MS as DC_PROMOTE_BACKOFF_MS_DEFAULT,
  DC_PROMOTE_MEASURE_TIMEOUT_MS,
  DC_PROMOTE_RATIO as DC_PROMOTE_RATIO_DEFAULT,
  dcPromoteTooSlow,
} from './route-policy';
