const SCRIPT_HEAD = [
  'uid=$(id -u 2>/dev/null) || uid=0',
  '[ -n "$uid" ] || uid=0',
  'if [ ! -e /sys/fs/cgroup/cgroup.controllers ]; then',
  '  printf \'VTMEM 1 %s 0\\n\' "$uid"',
  '  exit 0',
  'fi',
  'if ! systemctl --user show-environment >/dev/null 2>&1; then',
  '  printf \'VTMEM 1 %s 0\\n\' "$uid"',
  '  exit 0',
  'fi',
  'printf \'VTMEM 1 %s 1\\n\' "$uid"',
  'cgroup_num() {',
  '  if [ ! -r "$1" ]; then',
  "    printf '0\\n'",
  '    return',
  '  fi',
  '  _vt_val=$(cat "$1" 2>/dev/null) || _vt_val=',
  '  case "$_vt_val" in',
  "    max|'') printf '0\\n' ;;",
  '    *) printf \'%s\\n\' "$_vt_val" ;;',
  '  esac',
  '}',
  'while IFS=$(printf \'\\t\') read -r pane_id pid || [ -n "$pane_id" ]; do',
  '  if [ -z "$pane_id" ]; then',
  '    continue',
  '  fi',
  "  scope='-'",
  '  current=0',
  '  high=0',
  '  max=0',
  '  swapMax=0',
  '  oomKill=0',
  '  managed=0',
  '  if [ -n "$pid" ] && [ -r "/proc/${pid}/cgroup" ]; then',
  '    cg_line=$(sed -n \'s/^0:://p\' "/proc/${pid}/cgroup" | head -n 1)',
  '    last=${cg_line##*/}',
  '    case "$last" in',
  '      tmux-spawn-*.scope)',
  '        scope=$last',
  '        cg_dir="/sys/fs/cgroup${cg_line}"',
  '        current=$(cgroup_num "$cg_dir/memory.current")',
  '        high=$(cgroup_num "$cg_dir/memory.high")',
  '        max=$(cgroup_num "$cg_dir/memory.max")',
  '        swapMax=$(cgroup_num "$cg_dir/memory.swap.max")',
  '        high_raw=$(cat "$cg_dir/memory.high" 2>/dev/null) || high_raw=max',
  '        if [ "$high_raw" != "max" ] && [ -n "$high_raw" ]; then',
  '          managed=1',
  '        fi',
  '        if [ -r "$cg_dir/memory.events" ]; then',
  '          oomKill=$(sed -n \'s/^oom_kill[ 	]*//p\' "$cg_dir/memory.events" | head -n 1)',
  '          [ -n "$oomKill" ] || oomKill=0',
  '        fi',
  '        ;;',
  '    esac',
  '  fi',
  "  printf '%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n' \\",
  '    "$pane_id" "$pid" "$scope" "$current" "$high" "$max" "$swapMax" "$oomKill" "$managed"',
  "done <<'VTMEM_PANES'",
].join('\n');

export function buildSamplerScript(panes: Array<{ paneId: string; pid: number }>): string {
  const lines = panes.map((pane) => `${pane.paneId}\t${String(pane.pid)}`).join('\n');
  return `${SCRIPT_HEAD}\n${lines}${lines ? '\n' : ''}VTMEM_PANES\n`;
}
