import { USER_BUS_EXPORT_LINES } from './user-bus';

const SCRIPT_HEAD = [
  'uid=$(id -u 2>/dev/null) || uid=0',
  '[ -n "$uid" ] || uid=0',
  'limitsSupported=1',
  'reason=ok',
  'if [ ! -e /sys/fs/cgroup/cgroup.controllers ]; then',
  '  limitsSupported=0',
  '  reason=no-cgroup2',
  'else',
  ...USER_BUS_EXPORT_LINES,
  '  if ! systemctl --user show-environment >/dev/null 2>&1; then',
  '    limitsSupported=0',
  '    reason=no-user-systemd',
  '  fi',
  'fi',
  'printf \'VTMEM 2 %s %s %s\\n\' "$uid" "$limitsSupported" "$reason"',
  'cgroup_num() {',
  '  if [ ! -r "$1" ]; then',
  "    printf '\\n'",
  '    return',
  '  fi',
  '  _vt_val=$(cat "$1" 2>/dev/null) || _vt_val=',
  '  case "$_vt_val" in',
  "    max) printf '0\\n' ;;",
  "    '') printf '\\n' ;;",
  '    *) printf \'%s\\n\' "$_vt_val" ;;',
  '  esac',
  '}',
  'PSTAB=',
  'pstab_ok() {',
  "  printf '%s\\n' \"$PSTAB\" | awk '",
  '    BEGIN { found=0 }',
  '    $1 ~ /^[0-9]+$/ && $2 ~ /^[0-9]+$/ && $3 ~ /^[0-9]+$/ { found=1; exit }',
  '    END { if (!found) exit 1 }',
  "  '",
  '}',
  'pstab_load() {',
  '  if [ -n "$PSTAB" ]; then',
  '    return',
  '  fi',
  '  PSTAB=$(ps -Ao pid=,ppid=,rss= 2>/dev/null)',
  '  if pstab_ok; then',
  '    return',
  '  fi',
  '  PSTAB=$(ps -eo pid=,ppid=,rss= 2>/dev/null)',
  '  if pstab_ok; then',
  '    return',
  '  fi',
  '  PSTAB=$(ps ax -o pid=,ppid=,rss= 2>/dev/null)',
  '  if pstab_ok; then',
  '    return',
  '  fi',
  '  PSTAB=$(ps -o pid=,ppid=,rss= 2>/dev/null)',
  '  if pstab_ok; then',
  '    return',
  '  fi',
  '  PSTAB=-',
  '}',
  'rss_tree() {',
  '  pstab_load',
  '  if [ "$PSTAB" = - ]; then',
  "    printf '0\\n'",
  '    return',
  '  fi',
  '  printf \'%s\\n\' "$PSTAB" | awk -v target="$1" \'',
  '    { kb[$1]=$3; ch[$2]=ch[$2] " " $1 }',
  '    END {',
  '      n=1; stack[1]=target; seen[target]=1; total=0;',
  '      while (n > 0) {',
  '        p=stack[n]; n--;',
  '        if (p in kb) total += kb[p];',
  '        if (p in ch) {',
  '          m=split(ch[p], kids, " ");',
  '          for (i=1; i<=m; i++) {',
  '            k=kids[i];',
  '            if (k != "" && !(k in seen)) { seen[k]=1; n++; stack[n]=k }',
  '          }',
  '        }',
  '      }',
  '      printf "%.0f\\n", total * 1024;',
  "    }'",
  '}',
  'while IFS=$(printf \'\\t\') read -r pane_id pid || [ -n "$pane_id" ]; do',
  '  if [ -z "$pane_id" ]; then',
  '    continue',
  '  fi',
  "  scope='-'",
  '  current=0',
  '  high=0',
  '  max=0',
  '  swapMax=0',
  '  oomKill=0',
  '  managed=0',
  "  source='none'",
  '  if [ "$limitsSupported" = 1 ] && [ -n "$pid" ] && [ -r "/proc/${pid}/cgroup" ]; then',
  '    cg_line=$(sed -n \'s/^0:://p\' "/proc/${pid}/cgroup" | head -n 1)',
  '    last=${cg_line##*/}',
  '    case "$last" in',
  '      tmux-spawn-*.scope)',
  '        cg_dir="/sys/fs/cgroup${cg_line}"',
  '        current=$(cgroup_num "$cg_dir/memory.current")',
  '        if [ -n "$current" ]; then',
  "          source='cgroup'",
  '          scope=$last',
  '          high=$(cgroup_num "$cg_dir/memory.high")',
  '          [ -n "$high" ] || high=0',
  '          max=$(cgroup_num "$cg_dir/memory.max")',
  '          [ -n "$max" ] || max=0',
  '          swapMax=$(cgroup_num "$cg_dir/memory.swap.max")',
  '          # 读不到不是 0。0 是文件里的 max（无限）或数字 0；? 在比对时通配。',
  '          [ -n "$swapMax" ] || swapMax=\'?\'',
  '          high_raw=$(cat "$cg_dir/memory.high" 2>/dev/null) || high_raw=max',
  '          if [ "$high_raw" != "max" ] && [ -n "$high_raw" ]; then',
  '            managed=1',
  '          fi',
  '          if [ -r "$cg_dir/memory.events" ]; then',
  '            oomKill=$(sed -n \'s/^oom_kill[ \t]*//p\' "$cg_dir/memory.events" | head -n 1)',
  '            [ -n "$oomKill" ] || oomKill=0',
  '          fi',
  '        fi',
  '        ;;',
  '    esac',
  '  fi',
  '  if [ "$source" != "cgroup" ]; then',
  '    if [ -n "$pid" ]; then',
  '      pstab_load',
  '      current=$(rss_tree "$pid")',
  '      if [ -n "$current" ] && [ "$current" != 0 ]; then',
  "        source='rss'",
  '      else',
  '        current=0',
  "        source='none'",
  '      fi',
  '    fi',
  '  fi',
  "  printf '%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n' \\",
  '    "$pane_id" "$pid" "$scope" "$current" "$high" "$max" "$swapMax" "$oomKill" "$managed" "$source"',
  "done <<'VTMEM_PANES'",
].join('\n');

export function buildSamplerScript(panes: Array<{ paneId: string; pid: number }>): string {
  const lines = panes.map((pane) => `${pane.paneId}\t${String(pane.pid)}`).join('\n');
  return `${SCRIPT_HEAD}\n${lines}${lines ? '\n' : ''}VTMEM_PANES\n`;
}
