export {
  DOMAIN_AUTHORIZATION,
  DOMAIN_CERTIFICATE,
  DOMAIN_DELEGATION,
  DOMAIN_KEY_LOG,
  DOMAIN_LOGIN,
  DOMAIN_PEER,
  DelegationMethod,
  KeyLogSigner,
  KeyLogType,
  PeerPath,
  AddPasskeyPayloadSchema,
  AdmitNodePayloadSchema,
  AuthorizationSchema,
  CertificateSchema,
  ClearTotpPayloadSchema,
  DelegationSchema,
  DtlsFingerprintSchema,
  KdfParamsSchema,
  KeyLogRecordSchema,
  LoginSchema,
  PasskeyAssertionSchema,
  PeerHelloSchema,
  PeerTranscriptSchema,
  RemovePasskeyPayloadSchema,
  ResetRootPayloadSchema,
  RevokeNodePayloadSchema,
  RotateRootPayloadSchema,
  SetTotpPayloadSchema,
  TotpAadSchema,
  bytesEqual,
  bytesToHex,
  compareBytes,
  concatBytes,
  decodeAddPasskeyPayload,
  decodeAdmitNodePayload,
  decodeAuthorization,
  decodeBase64url,
  decodeCertificate,
  decodeClearTotpPayload,
  decodeDelegation,
  decodeKdfParams,
  decodeKeyLogRecord,
  decodeLogin,
  decodePasskeyAssertion,
  decodePeerTranscript,
  decodeRemovePasskeyPayload,
  decodeResetRootPayload,
  decodeRevokeNodePayload,
  decodeRotateRootPayload,
  decodeSetTotpPayload,
  decodeTotpAad,
  encodeAddPasskeyPayload,
  encodeAdmitNodePayload,
  encodeAuthorization,
  encodeBase64url,
  encodeCertificate,
  encodeClearTotpPayload,
  encodeDelegation,
  encodeKdfParams,
  encodeKeyLogRecord,
  encodeLogin,
  encodePasskeyAssertion,
  encodePeerTranscript,
  encodeRemovePasskeyPayload,
  encodeResetRootPayload,
  encodeRevokeNodePayload,
  encodeRotateRootPayload,
  encodeSetTotpPayload,
  encodeTotpAad,
  hexToBytes,
  nodeIdToHex,
  randomBytes,
  sha256,
  u32ToLe,
} from './encoding';
export type {
  AddPasskeyPayload,
  AdmitNodePayload,
  Authorization,
  Certificate,
  ClearTotpPayload,
  Delegation,
  DelegationMethod as DelegationMethodName,
  DtlsFingerprint,
  KdfParams,
  KeyLogRecord,
  KeyLogSigner as KeyLogSignerName,
  KeyLogType as KeyLogTypeName,
  Login,
  PasskeyAssertion,
  PeerHello,
  PeerPath as PeerPathName,
  PeerTranscript,
  RemovePasskeyPayload,
  ResetRootPayload,
  RevokeNodePayload,
  RotateRootPayload,
  SetTotpPayload,
  TotpAad,
} from './encoding';

export {
  ARGON2ID_HASH_LENGTH,
  ARGON2ID_ITERATIONS,
  ARGON2ID_MEMORY_KIB,
  ARGON2ID_PARALLELISM,
  KDF_SALT_LENGTH,
  deriveSeed,
  generateEd25519KeyPair,
  generateKdfParams,
  generateX25519KeyPair,
  rootKeyFromSeed,
  signEd25519,
  verifyEd25519,
} from './root-key';
export type { Ed25519KeyPair, RootKey, X25519KeyPair } from './root-key';

export {
  DELEGATION_CLOCK_SKEW_MS,
  DELEGATION_TTL_MS,
  buildPasskeyDelegation,
  createDelegation,
  delegationChallenge,
  verifyDelegation,
  verifyDelegationTimes,
} from './delegation';
export type {
  SignedDelegation,
  VerifyDelegationPasskey,
  VerifyDelegationResult,
  VerifyDelegationTimesError,
} from './delegation';

export { buildLogin, signLogin, verifyLogin } from './login';
export type { LoginErrorCode, VerifyLoginExpected, VerifyLoginResult } from './login';

export {
  KEY_LOG_SIGNER_MATRIX,
  applyKeyLogRecord,
  buildKeyLogRecord,
  computeRecordHash,
  detectFork,
  emptyUserKeyState,
  genesisHead,
  signKeyLogRecordWithRoot,
  verifyKeyLogChain,
  verifyKeyLogRecord,
} from './key-log';
export type {
  ApplyKeyLogCtx,
  ApplyKeyLogError,
  ApplyKeyLogResult,
  KeyLogEffect,
  KeyLogHead,
  KeyLogSignedRecord,
  PasskeyRecord,
  StoredNodeCert,
  UserKeyState,
  VerifyKeyLogChainError,
  VerifyKeyLogChainResult,
  VerifyKeyLogCtx,
  VerifyKeyLogError,
  VerifyKeyLogResult,
  VerifyPasskeyAssertion,
} from './key-log';

export {
  ENROLLMENT_TTL_MS,
  JOIN_TOKEN_BYTES,
  JOIN_TOKEN_CHARS,
  createEnrollment,
  createNodeCertificate,
  decodeJoinToken,
  encodeJoinToken,
  verifyNodeCertificate,
} from './enrollment';
export type {
  Enrollment,
  EnrollmentSigner,
  JoinToken,
  NodeCertificate,
  PasskeySigner,
} from './enrollment';

export {
  TOTP_DEFAULT_DIGITS,
  TOTP_DEFAULT_STEP,
  TOTP_SALT_PREFIX,
  deriveTotpKey,
  totpCode,
  verifyTotpCode,
} from './totp';
export type { TotpCodeOptions } from './totp';

export {
  TOTP_AEAD_ALG,
  decryptTotpSecret,
  encryptTotpSecret,
  totpAadBytes,
} from './totp-cipher';

export {
  PEER_SESSION_INFO_PREFIX,
  buildPeerTranscript,
  derivePeerSessionKeys,
  normalizeFingerprint,
  parseSdpFingerprint,
  signTranscript,
  verifyTranscript,
} from './peer-handshake';
export type { PeerSessionKeys } from './peer-handshake';

export {
  DOMAIN_UPLINK_AUTH,
  UplinkAuthSchema,
  decodeUplinkAuth,
  hubHostFromUrl,
  uplinkAuthMessage,
} from './uplink-auth';
export type { UplinkAuth } from './uplink-auth';
