export {
  DOMAIN_AUTHORIZATION,
  DOMAIN_CERTIFICATE,
  DOMAIN_DELEGATION,
  DOMAIN_KEY_LOG,
  DOMAIN_LOGIN,
  DOMAIN_PEER,
  DelegationMethod,
  KeyLogSigner,
  KeyLogType,
  PeerPath,
  AddPasskeyPayloadSchema,
  AdmitHubPayloadSchema,
  AdmitNodePayloadSchema,
  AuthorizationSchema,
  CertificateSchema,
  ClearTotpPayloadSchema,
  DelegationSchema,
  DtlsFingerprintSchema,
  KdfParamsSchema,
  KeyLogRecordSchema,
  LoginSchema,
  PasskeyAssertionSchema,
  PeerHelloSchema,
  PeerTranscriptSchema,
  RemovePasskeyPayloadSchema,
  ResetRootPayloadSchema,
  RetireHubPayloadSchema,
  RevokeNodePayloadSchema,
  RotateRootPayloadSchema,
  SetTotpPayloadSchema,
  TotpAadSchema,
  bytesEqual,
  bytesToHex,
  compareBytes,
  concatBytes,
  buildAdmitHubPayload,
  buildRetireHubPayload,
  decodeAddPasskeyPayload,
  decodeAdmitHubPayload,
  decodeAdmitNodePayload,
  decodeAuthorization,
  decodeBase32,
  decodeBase64url,
  decodeCertificate,
  decodeClearTotpPayload,
  decodeDelegation,
  decodeKdfParams,
  decodeKeyLogRecord,
  decodeLogin,
  decodePasskeyAssertion,
  decodePeerTranscript,
  decodeRemovePasskeyPayload,
  decodeResetRootPayload,
  decodeRetireHubPayload,
  decodeRevokeNodePayload,
  decodeRotateRootKeepPayload,
  decodeRotateRootPayload,
  decodeSetTotpPayload,
  decodeTotpAad,
  encodeAddPasskeyPayload,
  encodeAdmitHubPayload,
  encodeAdmitNodePayload,
  encodeAuthorization,
  encodeBase32,
  encodeBase64url,
  encodeCertificate,
  encodeClearTotpPayload,
  encodeDelegation,
  encodeKdfParams,
  encodeKeyLogRecord,
  encodeLogin,
  encodePasskeyAssertion,
  encodePeerTranscript,
  encodeRemovePasskeyPayload,
  encodeResetRootPayload,
  encodeRetireHubPayload,
  encodeRevokeNodePayload,
  encodeRotateRootKeepPayload,
  encodeRotateRootPayload,
  encodeSetTotpPayload,
  encodeTotpAad,
  hexToBytes,
  nodeIdToHex,
  randomBytes,
  sha256,
  u32ToLe,
} from './encoding';
export type {
  AddPasskeyPayload,
  AdmitHubPayload,
  AdmitNodePayload,
  Authorization,
  Certificate,
  ClearTotpPayload,
  Delegation,
  DelegationMethod as DelegationMethodName,
  DtlsFingerprint,
  KdfParams,
  KeyLogRecord,
  KeyLogSigner as KeyLogSignerName,
  KeyLogType as KeyLogTypeName,
  Login,
  PasskeyAssertion,
  PeerHello,
  PeerPath as PeerPathName,
  PeerTranscript,
  RemovePasskeyPayload,
  ResetRootPayload,
  RetireHubPayload,
  RevokeNodePayload,
  RotateRootKeepPayload,
  RotateRootKeepTotp,
  RotateRootPayload,
  SetTotpPayload,
  TotpAad,
} from './encoding';

export {
  ARGON2ID_HASH_LENGTH,
  ARGON2ID_ITERATIONS,
  ARGON2ID_MEMORY_KIB,
  ARGON2ID_PARALLELISM,
  KDF_SALT_LENGTH,
  deriveSeed,
  generateEd25519KeyPair,
  generateKdfParams,
  generateX25519KeyPair,
  rootKeyFromSeed,
  signEd25519,
  verifyEd25519,
} from './root-key';
export type { Ed25519KeyPair, RootKey, X25519KeyPair } from './root-key';

export {
  DELEGATION_CLOCK_SKEW_MS,
  DELEGATION_TTL_MS,
  buildPasskeyDelegation,
  createDelegation,
  delegationChallenge,
  verifyDelegation,
  verifyDelegationTimes,
} from './delegation';
export type {
  SignedDelegation,
  VerifyDelegationPasskey,
  VerifyDelegationResult,
  VerifyDelegationTimesError,
} from './delegation';

export { buildLogin, signLogin, verifyLogin } from './login';
export type { LoginErrorCode, VerifyLoginExpected, VerifyLoginResult } from './login';

export {
  generateWebCryptoEd25519KeyPair,
  signWithWebCryptoEd25519,
} from './webcrypto-ed25519';
export type { WebCryptoEd25519KeyPair } from './webcrypto-ed25519';

export {
  HUB_AUTH_RECORD_TYPES,
  KEYLOG_RECORD_COMPAT,
  RELAY_RECORD_TYPES,
  KEYLOG_TYPE_UNSUPPORTED_BY_NODES,
  KEY_LOG_SIGNER_MATRIX,
  MIN_HUB_AUTH_RECORD_VERSION,
  MIN_ROTATE_ROOT_KEEP_RECORD_VERSION,
  ROTATE_ROOT_KEEP_RECORD_TYPES,
  applyKeyLogRecord,
  buildKeyLogRecord,
  computeRecordHash,
  detectFork,
  emptyUserKeyState,
  genesisHead,
  signKeyLogRecordWithRoot,
  totpPayloadFromKeyLogRecord,
  verifyKeyLogChain,
  verifyKeyLogRecord,
} from './key-log';
export type {
  ApplyKeyLogCtx,
  ApplyKeyLogError,
  ApplyKeyLogResult,
  HubAuthorizationStatus,
  KeyLogEffect,
  KeyLogHead,
  KeyLogRecordCompatSpec,
  KeyLogSignedRecord,
  PasskeyRecord,
  StoredHubAuthorization,
  StoredNodeCert,
  UserKeyState,
  VerifyKeyLogChainError,
  VerifyKeyLogChainResult,
  VerifyKeyLogCtx,
  VerifyKeyLogError,
  VerifyKeyLogResult,
  VerifyPasskeyAssertion,
} from './key-log';

export {
  ENROLLMENT_TTL_MS,
  JOIN_TOKEN_BYTES,
  JOIN_TOKEN_CHARS,
  createEnrollment,
  createNodeCertificate,
  decodeJoinToken,
  encodeJoinToken,
  verifyNodeCertificate,
} from './enrollment';
export type {
  Enrollment,
  EnrollmentSigner,
  JoinToken,
  NodeCertificate,
  PasskeySigner,
} from './enrollment';

export {
  TOTP_DEFAULT_DIGITS,
  TOTP_DEFAULT_STEP,
  TOTP_SALT_PREFIX,
  deriveTotpKey,
  totpCode,
  verifyTotpCode,
} from './totp';
export type { TotpCodeOptions } from './totp';

export {
  TOTP_AEAD_ALG,
  decryptTotpSecret,
  encryptTotpSecret,
  totpAadBytes,
} from './totp-cipher';

export { rewrapTotpSecret } from './rewrap-totp';
export type { RewrapTotpInput } from './rewrap-totp';

export {
  PEER_SESSION_INFO_PREFIX,
  buildPeerTranscript,
  derivePeerSessionKeys,
  normalizeFingerprint,
  parseSdpFingerprint,
  signTranscript,
  verifyTranscript,
} from './peer-handshake';
export type { PeerSessionKeys } from './peer-handshake';

export {
  DOMAIN_UPLINK_AUTH,
  UplinkAuthSchema,
  decodeUplinkAuth,
  hubHostFromUrl,
  uplinkAuthMessage,
} from './uplink-auth';
export type { UplinkAuth } from './uplink-auth';

export { canonicalHubUrl } from './hub-url';

export {
  MIN_RELAY_RECORD_VERSION,
  MetaKeyPayloadSchema,
  RELAY_RECORD_MAX_RELAYS,
  RELAY_RECORD_MAX_URL_LEN,
  RELAY_RECORD_MAX_WRAP_ENTRIES,
  RelayListMode,
  RelayTargetSchema,
  RelayWrapEntrySchema,
  SetRelaysPayloadSchema,
  applyRelayKeyLogRecord,
  cloneRelayList,
  decodeMetaKeyPayload,
  decodeSetRelaysPayload,
  encodeMetaKeyPayload,
  encodeSetRelaysPayload,
  wrapEntryFromBytes,
  wrapEntryToBytes,
} from './relay-records';
export type {
  MetaKeyPayload,
  RelayListMode as RelayListModeName,
  RelayTargetPayload,
  RelayWrapEntryBytes,
  SetRelaysPayload,
  StoredRelayList,
  StoredRelayTarget,
} from './relay-records';
