// Auto-generated by scripts/fonts/build-fonts.ts
// Do not edit this file directly. Run `bun run build:fonts` to regenerate.
// Nerd Fonts v3.4.0
import type { FontManifestEntry } from './types';

export const FONT_MANIFEST: FontManifestEntry[] = [
  {
    id: "geist-mono",
    displayName: "Geist Mono",
    cssFamily: "GeistMonoVibeTerm",
    bundled: true,
    isDefault: true,
    files: { regular: "/fonts/GeistMonoNerdFontMono-Regular.woff2", bold: "/fonts/GeistMonoNerdFontMono-Bold.woff2" },
    subset: {
      regular: "/fonts/GeistMonoNerdFontMono-Regular-latin.woff2",
      bold: "/fonts/GeistMonoNerdFontMono-Bold-latin.woff2",
      unicodeRange: "U+0020-007E,U+00A0-00AC,U+00AE-0113,U+0116-012B,U+012E-0131,U+0134-0137,U+0139-013E,U+0141-0148,U+014A-014D,U+0150-017E,U+018F,U+0192,U+01CD-01CE,U+01E4-01E9,U+0218-021B,U+0237,U+0259,U+02B9,U+02BC,U+02C6-02C8,U+02D8-02DD,U+0300-0304,U+0306-0308,U+030A-030C,U+0312,U+0326-0328,U+0335-0338,U+1E20-1E21,U+1E80-1E85,U+1E9E,U+1EBC-1EBD,U+1EF2-1EF3,U+1EF8-1EF9,U+2013-2014,U+2018-201A,U+201C-201E,U+2020-2022,U+2026,U+2030,U+2032-2033,U+2039-203A,U+2044,U+2070,U+2074-2079,U+2080-2089,U+20AA,U+20AC,U+20B4,U+20B9,U+20BD,U+2107,U+2116-2117,U+2122,U+2153-2155,U+215B-215E,U+2190-2199,U+219D,U+21A9-21AA,U+21B0-21B1,U+21B3-21B5,U+21E4-21E5,U+21E7,U+2202,U+2206,U+220F,U+2211-2212,U+221A,U+221E,U+222B,U+2248,U+2260,U+2264-2265,U+2326-2327,U+232B,U+23CE,U+23FB-23FE,U+240B-240C,U+2423,U+2460-2468,U+24EA,U+24FF-259F,U+25B2-25B3,U+25B6-25B7,U+25BC-25BD,U+25C0-25C1,U+25CA-25CC,U+25CF,U+2630,U+2665,U+26A1,U+276C-2771,U+2776-277E,U+2B58,U+E0A0-E0A3,U+E0B0-E0C8,U+E0CA,U+E0CC-E0D2,U+E0D4",
      fullUnicodeRange: "U+A78B-A78C,U+E000-E00A,U+E0D6-E0D7,U+E200-E2A9,U+E300-E3E3,U+E5FA-E6B8,U+E700-E8EF,U+EA60-EA88,U+EA8A-EA8C,U+EA8F-EAC7,U+EAC9,U+EACC-EB09,U+EB0B-EB4E,U+EB50-EC1E,U+ED00-EFCE,U+F000-F381,U+F400-F533,U+F8FF,U+F0001-F1AF0",
    },
  },
  {
    id: "jetbrains-mono",
    displayName: "JetBrains Mono",
    cssFamily: "JetBrainsMonoVibeTerm",
    bundled: true,
    files: { regular: "/fonts/generated/jetbrains-mono/jetbrains-mono-regular.woff2", bold: "/fonts/generated/jetbrains-mono/jetbrains-mono-bold.woff2" },
  },
  {
    id: "fira-code",
    displayName: "Fira Code",
    cssFamily: "FiraCodeVibeTerm",
    bundled: true,
    files: { regular: "/fonts/generated/fira-code/fira-code-regular.woff2", bold: "/fonts/generated/fira-code/fira-code-bold.woff2" },
  },
  {
    id: "blex-mono",
    displayName: "Blex Mono (IBM Plex Mono)",
    cssFamily: "BlexMonoVibeTerm",
    bundled: true,
    files: { regular: "/fonts/generated/blex-mono/blex-mono-regular.woff2", bold: "/fonts/generated/blex-mono/blex-mono-bold.woff2" },
  },
  {
    id: "noto-sans-mono",
    displayName: "Noto Sans Mono",
    cssFamily: "NotoSansMVibeTerm",
    bundled: true,
    files: { regular: "/fonts/generated/noto-sans-mono/noto-sans-mono-regular.woff2", bold: "/fonts/generated/noto-sans-mono/noto-sans-mono-bold.woff2" },
  },
  {
    id: "zed-mono",
    displayName: "Zed Mono",
    cssFamily: "ZedMonoVibeTerm",
    bundled: true,
    files: { regular: "/fonts/generated/zed-mono/zed-mono-regular.woff2", bold: "/fonts/generated/zed-mono/zed-mono-bold.woff2" },
  },
  {
    id: "victor-mono",
    displayName: "Victor Mono",
    cssFamily: "VictorMonoVibeTerm",
    bundled: true,
    files: { regular: "/fonts/generated/victor-mono/victor-mono-regular.woff2", bold: "/fonts/generated/victor-mono/victor-mono-bold.woff2" },
  },
];

export const DEFAULT_FONT_ID = "geist-mono";
