export const SIDEBAR_COOKIE_NAME = 'sidebar_state';
export const SIDEBAR_COOKIE_MAX_AGE = 60 * 60 * 24 * 7;
export const SIDEBAR_WIDTH_MOBILE = '100vw';
export const SIDEBAR_WIDTH_ICON = '3rem';
export const SIDEBAR_KEYBOARD_SHORTCUT = 'b';
export const SIDEBAR_WIDTH_DEFAULT_PX = 320;
export const SIDEBAR_WIDTH_MIN_PX = 320;
export const SIDEBAR_WIDTH_MAX_RESERVE_PX = 450;
export const SIDEBAR_WIDTH_STORAGE_KEY = 'tmex_sidebar_width';
